version: '3.4'

# reference:
# https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data:/data
    secrets:
      - minio_root_user
      - minio_root_password
    environment:
      #- MINIO_ROOT_USER=minio
      #- MINIO_ROOT_PASSWORD=minio123
      - MINIO_ROOT_USER_FILE=minio_root_user
      - MINIO_ROOT_PASSWORD_FILE=minio_root_password

secrets:
  minio_root_user:
    file: ./minio-pure_root_user
  minio_root_password:
    file: ./minio-pure_root_password

volumes:
  data:
